### ISSUE TITLE
dynamic size

### ISSUE THREAD

**Issue by ronaldwidha** [Meti0X7CB/RoundPlayer#1]
Awesome rainmeter skin. Any plans on allowing dynamic sizes from .ini?

**Comment by Meti0X7CB** [comment]
Glad you liked it. Dynamic size is definitely my next move. I'm currently working on merging the EQ and Clock so they load together. I'm doing full-time school on the side 😃 so updating would be a little slow.

**Comment by Meti0X7CB** [comment]
Done in 4.0 release!
